/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}

declare global {
  const useEffect: typeof import('react').useEffect
  const useState: typeof import('react').useState
}